//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISOWebApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrukReport
    {
        public int ID { get; set; }
        public string NoPolisi { get; set; }
        public string Driver { get; set; }
        public string AsstDriver { get; set; }
        public string Tujuan { get; set; }
        public Nullable<System.DateTime> Berangkat { get; set; }
        public Nullable<System.DateTime> Pulang { get; set; }
        public string MuatanBerangkat { get; set; }
        public Nullable<decimal> QtyMuatanBerangkat { get; set; }
        public string MuatanPulang { get; set; }
        public Nullable<decimal> QtyMuatanPulang { get; set; }
    }
}
